### ISSUE TITLE
Подчистка репозитория

### ISSUE THREAD

**Issue by avasyukov** [Filatkin/TreeOOP#1]
Штатно в git-репозитории предполагается код + ресурсы + сценарии сборки. Там вполне может быть что-то ещё, если его наличие там уместно.

В данном случае точно стоит убрать:
- временные файлы сборки
- локальные настройки IDE, которые не переносимы между компьютерами

**Comment by Filatkin** [comment]
Вроде сделано

**Comment by avasyukov** [comment]
Подтверждаю, что всё стало полностью ок.
