### ISSUE TITLE
(*) Публичная и приватная части класса

### ISSUE THREAD

**Issue by avasyukov** [Filatkin/TreeOOP#2]
Формально сейчас всё корректно. Но функции, лежащие сбоку от класса, было бы идейно верно сделать методами -- тогда они скроются от внешнего кода в приватную часть класса. Сейчас их можно свободно вызывать извне. Это не кошмар-кошмар, но заметно нефэншуйно.

**Comment by Filatkin** [comment]
Вроде сделано

**Comment by avasyukov** [comment]
Подтверждаю, что всё стало полностью ок.
